//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpansesControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.ExpensesGroups = new HashSet<ExpensesGroup>();
        }
    
        public string Name { get; set; }
        public string ManagerName { get; set; }
        public string BugetPrefix { get; set; }
        public System.DateTime DateTime { get; set; }
        public int ManagerID { get; set; }
        public int ID { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<ExpensesGroup> ExpensesGroups { get; set; }
    }
}
