//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpansesControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestEmpData
    {
        public int UserId { get; set; }
        public string Mail { get; set; }
        public string SAmAccountName { get; set; }
        public string RstBudgetprefix { get; set; }
        public Nullable<int> UserType { get; set; }
        public string ManadgerSAmAccountName { get; set; }
        public string FinanceSAmAccountName { get; set; }
    }
}
